name: "Chromium Browser to HA"
slug: "chromium_browser_to_ha"
description: "Provides a full Chromium browser environment via noVNC in Home Assistant"
version: "1.0.1"

arch:
  - amd64
  - armhf
  - armv7
  - aarch64

# Port mapping: Container port 8080 → Host port 8080
ports:
  8080/tcp: 8080

# Image name without underscores
image: "local/chromium-browser:latest"

# You can either use `full_access: true` OR list capabilities:
# privileged:
#   - SYS_ADMIN
#   - NET_ADMIN
full_access: true

# Start mode & boot
startup: application
boot: manual

# Instead of 'auto_uart', use 'uart' if needed. 
uart: false

# New schema format: dictionary
schema:
  resolution: str
  kiosk: bool
  start_url: str
  vnc_password: str

# Default options that user can override
options:
  resolution: "1280x800"
  kiosk: false
  start_url: "https://google.com"
  vnc_password: ""
