name: "Chromium Browser to HA"
slug: "chromium-browser-to-ha"
version: "1.1.0"
description: "Provides a full Chromium browser environment via noVNC in Home Assistant"

arch:
  - amd64
  - armhf
  - armv7
  - aarch64

ports:
  8080/tcp: 8080

# IMPORTANT: Use a valid format for 'image'
image: "ghcr.io/gli347/chromiumbrowser:latest"

full_access: true

startup: application
boot: manual
uart: false

schema:
  resolution: str
  kiosk: bool
  start_url: str
  vnc_password: str

options:
  resolution: "1280x800"
  kiosk: false
  start_url: "https://google.com"
  vnc_password: ""
