name: "Chromium Browser (Ingress)"
slug: "chromium_browser_ingress"
version: "1.2.1"
description: "Chromium via noVNC in HA with Ingress"

arch:
  - amd64
  - armhf
  - armv7
  - aarch64

# Enable Ingress and pick a stable internal port
ingress: true
ingress_port: 8099

panel_title: "Chromium"
panel_icon: "mdi:web"

# No 'ports:' block here

# Docker build or image
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  armhf: "ghcr.io/home-assistant/armhf-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"

startup: application
boot: manual
full_access: true
uart: false

schema:
  resolution: str
  kiosk: bool
  start_url: str
  vnc_password: str

options:
  resolution: "1280x800"
  kiosk: false
  start_url: "https://google.com"
  vnc_password: ""

  resolution: "1280x800"
  kiosk: false
  start_url: "https://google.com"
  vnc_password: ""
