name: "Chromium Browser to HA"
version: "1.0.0"
slug: "chromium_browser_to_ha"
description: "Provides a full Chromium browser environment via noVNC in Home Assistant"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
ports:
  8080/tcp: 8080
image: local/chromium_browser_to_ha:latest
privileged: true
startup: application
boot: manual
auto_uart: false
host_network: false

# Valgfri konfigurasjon for å la brukeren justere parametere:
schema:
  - name: resolution
    description: "Screen resolution (WxH)"
    type: string
    default: "1280x800"
  - name: kiosk
    description: "Enable kiosk mode?"
    type: boolean
    default: false
  - name: start_url
    description: "Which URL should Chromium open on startup?"
    type: string
    default: "https://google.com"
  - name: vnc_password
    description: "Optional VNC password (leave empty for no password)"
    type: string
    default: ""

