name: "Chromium Browser (Ingress)"
slug: "chromium-browser"
version: "1.2.0"
description: "Chromium via noVNC with Ingress"

arch:
  - amd64
  - armhf
  - armv7
  - aarch64

# Ingress recommended
ingress: true
ingress_port: 0
panel_title: "Chromium"
panel_icon: "mdi:web"

# Remove 'image:' and specify base images for each arch
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  armhf: "ghcr.io/home-assistant/armhf-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"

startup: application
boot: manual
full_access: true
uart: false

schema:
  resolution: str
  kiosk: bool
  start_url: str
  vnc_password: str

options:
  resolution: "1280x800"
  kiosk: false
  start_url: "https://google.com"
  vnc_password: ""
