name: "Chromium Browser (Ingress)"
slug: "chromium_browser_ingress"
version: "1.1.0"
description: "Chromium browser environment via noVNC, displayed in HA sidebar with Ingress"

arch:
  - amd64
  - armhf
  - armv7
  - aarch64

# Enable Ingress
ingress: true

# Let Supervisor pick an available port automatically:
ingress_port: 0

# (Optional) Provide a title/icon for the sidebar.
panel_title: "Chromium"
panel_icon: "mdi:web"

# No 'ports:' here, because Ingress doesn't expose anything on the host
# If you had 'ports:', remove them for a pure Ingress approach.

# Docker image or build info
image: "docker.io/gli347/chromiumbrowser:latest"
startup: application
boot: manual
uart: false
full_access: true

schema:
  resolution: str
  kiosk: bool
  start_url: str
  vnc_password: str

options:
  resolution: "1280x800"
  kiosk: false
  start_url: "https://google.com"
  vnc_password: ""
