name: "Google Chrome Browser (Ingress)"
slug: "google_chrome_browser_ingress"
version: "1.2.1"
description: "Google Chrome via noVNC in HA with Ingress"

arch:
  - amd64
  - armhf
  - armv7
  - aarch64

# Enable Ingress and pick a stable internal port
ingress: true
ingress_port: 8099

panel_title: "Google Chrome"
panel_icon: "mdi:web"

# No 'ports:' block here because we're using Ingress (no direct external port)

# Build from base images for each architecture
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  armhf: "ghcr.io/home-assistant/armhf-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"

startup: application
boot: manual
full_access: true
uart: false

# Define user-configurable fields
schema:
  resolution: str
  kiosk: bool
  start_url: str
  vnc_password: str

# Default values for each field in schema
options:
  resolution: "1280x800"
  kiosk: false
  start_url: "https://google.com"
  vnc_password: ""
